site_name: Portfolio Alfred Narjes

nav:
  - Home: index.md
  - Projects:
    - Rainbow Snake: projects/rainbowSnake.md
    - Ping-Pong-Gone-Wrong: projects/pingPongGoneWrong.md
    - CSV Manipulation: projects/csvManipulation.md
    - Bad UI/UX: projects/badUI.md
  - Credits: credits.md


extra_css:
  - ./css/style.css
  - ./css/projects.css
  # - ./css/bootstrap/bootstrap.css
  # - ./css/bootstrap/bootstrap.min.css
  # - ./css/bootstrap/bootstrap-theme.css
  # - ./css/bootstrap/bootstrap-theme.min.css


extra_javascript:
    - ./js/main.js
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
    # - ./js/bootstrap/bootstrap.js
    # - ./js/bootstrap/bootstrap.min.js

theme:
  name: material
  icon:
    logo: fontawesome/solid/laptop-code
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.bottom
    - navigation.expand
    # - navigation.instant
    # - navigation.instant.progress
    # - navigation.instant.prefetch
    - navigation.tracking
    - navigation.indexes
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: teal
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: teal

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/andiblup
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/andiblup
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/alfrednarjes/

markdown_extensions:
  - admonition
  - pymdownx.arithmatex
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.progressbar
  - codehilite
  - pymdownx.superfences
  - attr_list