name: Deploy MkDocs to gh-pages

on:
  push:
    branches:
      - dev   # Triggert nur bei Push auf 'dev'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # Wichtig: damit wir Branches wechseln können

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-material  # falls du mkdocs-material nutzt

      - name: Build mkdocs
        run: mkdocs build --clean

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          force_orphan: true
